FROM ruby:latest

RUN apt update -y && apt install -y gcc make cmake git curl wget
#ADD calico /calico
RUN git clone https://github.com/projectcalico/calico.git
WORKDIR /calico

RUN gem install bundler jekyll

#RUN bundle install
RUN bundle exec jekyll build


FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=0 /calico/_site/* /usr/share/nginx/html/
