FROM ruby:latest

ADD calico /calico
WORKDIR /calico
RUN apk add gcc make cmake git curl wget
RUN gem install bundler
RUN gem install jekyll
RUN bundle install
RUN bundle exec jekyll build


FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=0 /calico/_site/* /usr/share/nginx/html/
