FROM debian:buster AS builder
WORKDIR /
RUN apt update -y
RUN apt install -y git curl wget sudo python3 python3-pip openssl zlib1g-dev libpcre3 libpcre3-dev openssl libssl-dev curl
RUN mkdir -p /etc/curlssl/
RUN curl https://curl.se/ca/cacert.pem -o  /etc/curlssl/cacert.pem

RUN git clone  https://github.com/ceph/ceph.git
WORKDIR /ceph
RUN pip3 install sphinxcontrib-ditaa
RUN apt install -y ditaa
RUN sh -c '/bin/echo -e "\ny\ny"' | sudo apt-get install `cat doc_deps.deb.txt`
RUN admin/build-doc

RUN curl --silent --remote-name --location https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm
RUN mv cephadm build-doc/output


FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html
COPY --from=builder /ceph/build-doc/output /usr/share/nginx/html
#COPY --from=ceph-io /ceph.io/dist/ /usr/share/nginx/html
