name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sh build-docker.sh
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
        DOCKER_USER: ${{secrets.docker_user}}
