name: kubernetes-website-mirror
on:
    push:
      branches:
        - master
    schedule:
      - cron: '00 01 * * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: "step-1: prepare"
      run: sh build-prepare.sh
      env:
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_ALI_PASSWORD: ${{ secrets.docker_ali_password }}
          DOCKER_USER: ${{secrets.docker_user}}
          DOCKER_ALI_USER: ${{secrets.docker_ali_user}}
          DOCKER_IMAGE: ${{secrets.docker_image}}
    - name: "step-2: build kubernetes tools"
      run:  sh build-kubernetes-tools.sh
    - name: "step-3: build istio  wiki"
      run:  sh build-istio-io-wiki.sh
    - name: "step-4: build calico  wiki"
      run:  sh build-calico-docs.sh
    - name: "step-5: build nginx-quick  wiki"
      run:  sh build-nginx-quick-http3.sh
    - name: "step-6: build ceph  wiki"
      run: sh build-ceph-io-wiki.sh
    - name: "step-last clean workspace"
      run: sh clean.sh
