name: kubernetes-website-mirror
on:
    push:
      branches:
        - master
    schedule:
      - cron: '00 01 */12 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: excute build
      run: sh build-docker.sh
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
        DOCKER_USER: ${{secrets.docker_user}}
        DOCKER_IMAGE: ${{secrets.docker_image}}

