name: kubernetes-website-mirror
on:
    push:
      branches:
        - master
    schedule:
      - cron: '00 01 */12 * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: "step-1: prepare"
      run: sh build-prepare.sh
      env:
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_ALI_PASSWORD: ${{ secrets.docker_ali_password }}
          DOCKER_USER: ${{secrets.docker_user}}
          DOCKER_ALI_USER: ${{secrets.docker_ali_user}}
          DOCKER_IMAGE: ${{secrets.docker_image}}
#    - name: "step-2: build  kubernetes and tools"
#      run:  sh build-docker.sh
    - name: "step-3: build soft wiki"
      run:  sh build-soft-wiki.sh
    - name: "step-4 clean workspace"
      run: sh clean.sh
