name: kubernetes-website-mirror
on:
    push:
      branches:
        - dev
        - main
    schedule:
      - cron: '00 19 1 * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: "step-1: prepare"
      run: sh build-prepare.sh
      env:
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          DOCKER_ALI_PASSWORD: ${{ secrets.docker_ali_password }}
          DOCKER_USER: ${{secrets.docker_user}}
          DOCKER_ALI_USER: ${{secrets.docker_ali_user}}
          DOCKER_IMAGE: ${{secrets.docker_image}}
    - name: "step-dev: dev test"
      run: sh dev-test.sh
#    - name: "step-11: build-coturn-server"
#      run: sh build-coturn-server.sh
#    - name: "clean5 workspace"
#      run: sh clean.sh
#    - name: "step-10: build-janus-server"
#      run: sh build-janus-server.sh
#    - name: "clean4 workspace"
#      run: sh clean.sh
#    - name: "step-9: build ovn"
#      run: sh build-ovn.sh
    - name: "step-8: build developer.chrome.com"
      run: sh build-developer-chrome-com.sh
    - name: "step-3: build istio  wiki"
      run:  sh build-istio-io-wiki.sh
#    - name: "clean3 workspace"
#      run: sh clean.sh
#    - name: "step-4: build calico  wiki"
#      run:  sh build-calico-docs.sh
#    - name: "step-5: build nginx-quick  wiki"
#      run:  sh build-nginx-quick-http3.sh
    - name: "step-6: build ceph  wiki"
      run: sh build-ceph-io-wiki.sh
#    - name: "step-7: build freeswitch-v1-x"
#      run: sh build-freeswitch-v1-x.sh
#    - name: "clean2 workspace"
#      run: sh clean.sh
    - name: "step-2: build kubernetes tools"
      run:  sh build-kubernetes-tools.sh
    - name: "clean1 workspace"
      run: sh clean.sh
