name: kubernetes-website-mirror
on:
    push:
      branches:
        - master
    schedule:
      - cron: '00 01 */12 * *'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: excute build
      run:
          -/bin/sh
          - -c
          - |
            sh build-prepare.sh
            sh build-docker.sh

      env:
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
        DOCKER_USER: ${{secrets.docker_user}}
        DOCKER_IMAGE: ${{secrets.docker_image}}

