name: kubernetes-website-mirror
on:
    push:
      branches:
        - master
    schedule:
      - cron: '00 01 */12 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v2.3.0
    - name: Build the Docker image
      run: sh build-docker.sh
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
        DOCKER_USER: ${{secrets.docker_user}}
        DOCKER_IMAGE: ${{secrets.docker_image}}

