name: Docker Image CI

on:
  push
  schedule:
    - cron: '00 00 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: sh build-docker.sh
      env:
        DOCKER_PASSWORD: ${{ secrets.docker_password }}
        DOCKER_USER: ${{secrets.docker_user}}
        DOCKER_IMAGE: ${{secrets.docker_image}}

